Repository hms-dbmi/pic-sure, pull requests merged in 2023-12, with the labels that each got.

#164 [ALS-0000] Fix aggregate resource
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
Labels: bug

#169 [ALS-5482] - PIC-SURE Code formatting
  README.md
  code-formatting/eclipse-formatter.xml
  code-formatting/pre-commit.sh
  pom.xml
Labels: enhancement

#166 [ALS-5061] Remove HSAPIResource
  pic-sure-api-wildfly/pom.xml
  pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/HSAPIResourceIT.java
  pic-sure-resources/pic-sure-hsapi-resource/README.md
  pic-sure-resources/pic-sure-hsapi-resource/pom.xml
  pic-sure-resources/pic-sure-hsapi-resource/src/main/java/edu/harvard/hms/dbmi/avillach/HSAPIResourceRS.java
  pic-sure-resources/pic-sure-hsapi-resource/src/main/java/edu/harvard/hms/dbmi/avillach/JAXRSConfiguration.java
  pic-sure-resources/pic-sure-hsapi-resource/src/main/resources/webapp/META-INF/context.xml
  pic-sure-resources/pic-sure-hsapi-resource/src/main/resources/webapp/WEB-INF/beans.xml
  pic-sure-resources/pic-sure-hsapi-resource/src/main/resources/wildflyConfiguration/standalone.xml
  pic-sure-resources/pom.xml
Labels: enhancement

#170 Release config
  .github/release.yml
Labels: ignore-for-release

#171 Add deps to label checker
  .github/workflows/label-checker.yml
Labels: ignore-for-release

#167 [ALS-3978] Update version handling in multiple pom.xml files
  pic-sure-api-data/pom.xml
  pic-sure-api-war/pom.xml
  pic-sure-initializer/pom.xml
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/pom.xml
  pic-sure-resources/pic-sure-ga4gh-dos/pom.xml
  pic-sure-resources/pic-sure-passthrough-resource/pom.xml
  pic-sure-resources/pic-sure-resource-api/pom.xml
  pic-sure-resources/pic-sure-visualization-resource/pom.xml
  pic-sure-resources/pom.xml
  pic-sure-util/pom.xml
  pom.xml
Labels: enhancement

#173 Release/0008
  pic-sure-api-data/pom.xml
  pic-sure-api-war/pom.xml
  pic-sure-api-wildfly/pom.xml
  pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/HSAPIResourceIT.java
  pic-sure-initializer/pom.xml
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/pom.xml
  pic-sure-resources/pic-sure-ga4gh-dos/pom.xml
  pic-sure-resources/pic-sure-hsapi-resource/README.md
  pic-sure-resources/pic-sure-hsapi-resource/pom.xml
  pic-sure-resources/pic-sure-hsapi-resource/src/main/java/edu/harvard/hms/dbmi/avillach/HSAPIResourceRS.java
  pic-sure-resources/pic-sure-hsapi-resource/src/main/java/edu/harvard/hms/dbmi/avillach/JAXRSConfiguration.java
  pic-sure-resources/pic-sure-hsapi-resource/src/main/resources/webapp/META-INF/context.xml
  pic-sure-resources/pic-sure-hsapi-resource/src/main/resources/webapp/WEB-INF/beans.xml
  pic-sure-resources/pic-sure-hsapi-resource/src/main/resources/wildflyConfiguration/standalone.xml
  pic-sure-resources/pic-sure-passthrough-resource/pom.xml
  pic-sure-resources/pic-sure-resource-api/pom.xml
  pic-sure-resources/pic-sure-visualization-resource/pom.xml
  pic-sure-resources/pom.xml
  pic-sure-util/pom.xml
  pom.xml
Labels: ignore-for-release
