Repository hms-dbmi/pic-sure, pull requests merged in 2023-09, with the labels that each got.

#140 [ALS-4906] Add Variant Explorer in GIC Common Area
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
Labels: enhancement

#142 Release 3
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
Labels: ignore-for-release

#141 [ALS-4467] other study bar on var dist fix
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
  pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/DataProcessingService.java
  pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/VisualizationUtil.java
Labels: bug

#144 [ALS-4980] pic sure medium findings
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/test/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRSAcceptanceTests.java
  pic-sure-resources/pic-sure-ga4gh-dos/src/main/java/edu/harvard/hms/dbmi/avillach/GA4GHResourceRS.java
  pic-sure-resources/pic-sure-hsapi-resource/src/main/java/edu/harvard/hms/dbmi/avillach/HSAPIResourceRS.java
  pic-sure-resources/pic-sure-passthrough-resource/src/test/java/edu/harvard/hms/dbmi/avillach/resource/passthru/PassThroughResourceRSTest.java
  pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/IResourceRS.java
  pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/VisualizationService.java
  pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/HttpClientUtil.java
  pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/converter/UUIDParamConverter.java
  pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/converter/UUIDParamConverterProvider.java
Labels: enhancement

#145 Update github-actions-deploy-snapshots.yml
  .github/workflows/github-actions-deploy-snapshots.yml
Labels: ignore-for-release
