Repository hms-dbmi/pic-sure, pull requests merged in 2023-11, with the labels that each got.

#154 [ALS-5000] BDC: old version of log4j sitting in a repo
  pic-sure-resources/pom.xml
  pom.xml
Labels: dependencies, ignore-for-release

#156 Stat vis fixes and enhancements
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/service/HeaderFilter.java
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/service/RequestScopedHeader.java
  pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/ApplicationProperties.java
  pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/VisualizationResource.java
  pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/DataProcessingService.java
  pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/HpdsService.java
  pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/VisualizationService.java
  pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/Utilities.java
  pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/VisualizationUtil.java
Labels: enhancement

#155 [ALS-5065] Create proxy endpoint to enable dockerized services
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/PicsureRS.java
  pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/IResourceRS.java
  pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/ProxyWebClient.java
  pic-sure-resources/pic-sure-resource-api/src/test/java/edu/harvard/dbmi/avillach/service/ProxyWebClientTest.java
  pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/HttpClientUtil.java
Labels: enhancement

#157 Site of origin
  pic-sure-api-data/src/main/java/edu/harvard/dbmi/avillach/data/entity/DataSharingStatus.java
  pic-sure-api-data/src/main/java/edu/harvard/dbmi/avillach/data/entity/Site.java
  pic-sure-api-data/src/main/java/edu/harvard/dbmi/avillach/data/repository/SiteRepository.java
  pic-sure-api-data/src/main/resources/db/sql/V6__ADD_SITE_TABLE.sql
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/PicsureRS.java
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/security/JWTFilter.java
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/PicsureInfoService.java
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/PicsureQueryService.java
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/PicsureSearchService.java
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/SiteParsingService.java
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/SystemService.java
  pic-sure-api-war/src/main/resources/META-INF/persistence.xml
  pic-sure-api-war/src/test/java/edu/harvard/dbmi/avillach/PicsureInfoServiceTest.java
  pic-sure-api-war/src/test/java/edu/harvard/dbmi/avillach/PicsureQueryServiceTest.java
  pic-sure-api-war/src/test/java/edu/harvard/dbmi/avillach/PicsureSearchServiceTest.java
  pic-sure-api-war/src/test/java/edu/harvard/dbmi/avillach/service/SiteParsingServiceTest.java
  pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/AggregateResourceIT.java
  pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/GnomeI2B2ResourceIT.java
  pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/HSAPIResourceIT.java
  pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/IRCTResourceIT.java
  pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/PicsureInfoServiceIT.java
  pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/PicsureQueryServiceIT.java
  pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/PicsureSearchServiceIT.java
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/test/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRSAcceptanceTests.java
  pic-sure-resources/pic-sure-ga4gh-dos/src/main/java/edu/harvard/hms/dbmi/avillach/GA4GHResourceRS.java
  pic-sure-resources/pic-sure-passthrough-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/passthru/PassThroughResourceRS.java
  pic-sure-resources/pic-sure-passthrough-resource/src/test/java/edu/harvard/hms/dbmi/avillach/resource/passthru/PassThroughResourceRSTest.java
  pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/FederatedQueryRequest.java
  pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/GeneralQueryRequest.java
  pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/QueryRequest.java
  pic-sure-resources/pic-sure-resource-api/src/test/java/edu/harvard/dbmi/avillach/domain/QueryRequestTest.java
  pic-sure-resources/pic-sure-resource-api/src/test/java/edu/harvard/dbmi/avillach/service/ResourceWebClientTest.java
  pic-sure-resources/pic-sure-visualization-resource/src/test/java/edu/harvard/hms/dbmi/avillach/resource/visualization/VisualizationResourceTests.java
  pic-sure-resources/pic-sure-visualization-resource/src/test/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/DataServiceTests.java
  pic-sure-resources/pic-sure-visualization-resource/src/test/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/HpdsServiceTests.java
Labels: enhancement

#158 [ALS-5356] _harmonized_consent displayed in Open Variable Distributions
  pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/DataProcessingService.java
Labels: bug, ignore-for-release

#159 [ALS-0000] Checkmarx Fix - Check domain of proxy request
  pic-sure-resources/pic-sure-resource-api/pom.xml
  pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/ProxyWebClient.java
  pic-sure-resources/pic-sure-resource-api/src/test/java/edu/harvard/dbmi/avillach/service/ProxyWebClientTest.java
Labels: ignore-for-release

#161 [ALS-5422] Add persistence.xml to visualization resource
  pic-sure-resources/pic-sure-visualization-resource/src/main/resources/META-INF/persistence.xml
Labels: bug

#162 Syncing the release branch with master after a hotfix
  pic-sure-resources/pic-sure-visualization-resource/src/main/resources/META-INF/persistence.xml
Labels: ignore-for-release
