Repository hms-dbmi/pic-sure, pull requests merged in 2024-09, with the labels that each got.

#202 ALS-7014: Implement handling of signed URLs from HPDS
  pic-sure-api-data/pom.xml
  pic-sure-api-war/pom.xml
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/PicsureRS.java
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/PicsureQueryService.java
  pic-sure-resources/pic-sure-aggregate-data-sharing-resource/pom.xml
  pic-sure-resources/pic-sure-ga4gh-dos/pom.xml
  pic-sure-resources/pic-sure-passthrough-resource/pom.xml
  pic-sure-resources/pic-sure-resource-api/pom.xml
  pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/SignedUrlResponse.java
  pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/ResourceWebClient.java
  pic-sure-resources/pic-sure-resource-api/src/test/java/edu/harvard/dbmi/avillach/domain/SignedUrlResponseTest.java
  pic-sure-resources/pic-sure-visualization-resource/pom.xml
  pic-sure-resources/pom.xml
  pic-sure-util/pom.xml
  pom.xml
Labels: enhancement

#203 Fix snapshot build
  .github/workflows/github-actions-deploy-snapshots.yml
Labels: dependencies

#205 [ALS-6921] Implement Open Access in PSAMA
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/PicSureWarInit.java
  pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/security/JWTFilter.java
  pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/VisualizationService.java
Labels: enhancement

#206 Visualization should not need tokens now in Open Access
  pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/HpdsService.java
Labels: bug
